Fix missing-prototypes
main-settings-dialog.c:282:1: error: 'tabs_combo_box_new' was used with no prototype before its definition [-Werror=missing-prototypes]
main-settings-dialog.c:301:1: error: 'size_combo_box_new' was used with no prototype before its definition [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>